### ISSUE TITLE
v2 Roadmap

### ISSUE THREAD

**Issue by bumbeishvili** [bumbeishvili/org-chart#14]
Merged PR - https://github.com/bumbeishvili/org-chart/pull/70

# Development
* [x] Before proceeding with features, simplify code as much as possible

# Bugs and small features
* [x] One element data array
      °  #41
* [x] Unsafe use of eval 
      ° #40 
* [x] Node image group - foreign object order 
      ° #34
* [x] Plus Minus Button
      °  #33
      ° #11
      ° #46 Check
* [x] Root node collapse

# FAQ 
 * [x] Provide chart update code snippet 
      °  #8 

# Enhancements
* [x] d3 flextree 
      ° #55 
* [x] Export current or full view 
      ° #44 
* [x] Responsivness 
      ° #37 
* [x] Better default design
      ° #62 
# More flexible content 
   * [x] Allow providing node content via HTML (properties like, highlighted, collapsed, expanded, subordinates count, subordinates array method,  will be included, which allows the user for custom styling). It allows the user to provide custom content for each case. 
      °  #9 
      °  #10 
   * [x] Allow providing custom properties id, and parentId
   * [x] Allow providing expand, collapse content (properties like, highlighted, collapsed, expanded, subordinates count, subordinates array method,  will be included, which allows the user custom styling).  
      ° #47

# UX
* [x] neighbourMargin
* [x] fit - zoom to bounds
* [x] zoom in
* [x] zoom out
* [x] Full Screen
* [x] Expand All

# Search & Highlight (#2 )
* [x]  Add option for node centering
    ° #18 
* [x]  Higlighting nodes
* [x] Add option for expand 
* [x] collapse 
* [x] node centering

# New Features (Misc)
* [x] Add horizontal layout option - 
       ° #6 
       ° #42 
       ° #20
* [x] Option for compact vertical layout - [Much like this](https://davidb.dev/project/leadership-connect-org-chart) 
      °  #50
      °  #18 
* [x] Adding ability to connect multiple nodes to each other 
      ° #59 
      ° #57
     ° #3

# Fix existing bugs and add integration samples
   * [x] Angular integration 
      ° #13 
   * [x] React Integration - 
      ° #5 
   * [x] Vue integration

# Upgrade
  * [x] Upgrade to d3.v7
  * [x] Convert as d3 plugin 
      ° #35 

# Misc
* [x] Make almost all code pieces updatable
* [x] NPM publish

## Examples
1. [x] <img width="224" alt="Screenshot 2021-07-18 at 09 59 14" src="https://user-images.githubusercontent.com/6873202/126057327-eef1ba7a-41dd-48fb-8544-1e5d06cc4f43.png">

## Private Consultation
* [x] Consultation
* [x] Mentions
* [x] Articles
